const FURNITURE_TYPE = {
  BED: 'BED',
  SOFAS: 'SOFAS',
  DINING_SET: 'DINING_SET',
  DINING_TABLE: 'DINING_TABLE',
  DINING_CHAIR: 'DINING_CHAIR',
  HOME_OTHER: 'HOME_OTHER',
  OFFICE_CHAIR: 'OFFICE_CHAIR',
  BOARDROOM_TABLE: 'BOARDROOM_TABLE',
  WORKSTATION: 'WORKSTATION',
  OFFICE_SOFA: 'OFFICE_SOFA',
  OFFICE_DESK: 'OFFICE_DESK',
  OFFICE_OTHER: 'OFFICE_OTHER',
};

const FURNITURE_CATEGORY = {
  CHAIRS: 'CHAIRS',
  CABINETS: 'CABINETS',
  HOME_FURNITURE: 'HOME_FURNITURE',
  WORKSTATIONS: 'WORKSTATIONS',
  EXECUTIVE_SOFA: 'EXECUTIVE_SOFA',
  OFFICE_DESK: 'OFFICE_DESK',
  RECEPTION: 'RECEPTION',
};


const FURNITURE_MATERIAL = {
  WOOD: 'WOOD',
  PLASTIC: 'PLASTIC',
  METAL: 'METAL',
  GLASS: 'GLASS',
  FABRIC: 'FABRIC',
};

module.exports = {
  FURNITURE_TYPE,
  FURNITURE_CATEGORY,
  FURNITURE_MATERIAL,
};